- name: Condition demo
  hosts: local
  connection: local

  vars:
    number: 78

  tasks:
    - name: Print if number is less than 100
      when: number < 100
      ansible.builtin.debug:
        msg: "Given number {{ number }} is less than 100"

  
    - name: Print if number is greater than 100
      when: number > 100
      ansible.builtin.debug:
        msg: "Given number {{ number }} is greater than 100" 