---
- name: Ansible datatypes
  hosts: localhost
  connection: local

  vars:
    duration: 120
    course: DevOps
    is_live: true

    tools:
      - linux
      - shell
      - ansible

    concepts:
      CI: Jenkins
      scripting: "Shell, Ansible, Terraform, Python"

  tasks:
    - name: Print course information
      ansible.builtin.debug:
        msg: "Course is: {{ course }}, duration: {{ duration }}, is live: {{ is_live }}, tools are: {{ tools }}, concepts are: {{ concepts }}"