- name: play-book-1 and task
  hosts: local
  connection: local

  tasks: # list of tasks
 
   - name: playbook-1 and task-1
     ansible.builtin.debug:
      msg: "play book-1 and task-1"
   
   - name: playbook-1 and task-2
     ansible.builtin.debug:
      msg: "play book-1 and task-2"
   
   - name: playbook-2 and task-1
     ansible.builtin.debug:
      msg: "play book-1 and task-1"
   
   - name: playbook-2 and task-2
     ansible.builtin.debug:
      msg: "play book-1 and task-1"