- name: variables from the inventory
  hosts: local
  connection: local
  tasks: #tasks

   - name: variables from the inventory
     ansible.builtin.debug:
         msg: "Hello i am lerning {{ course }}, duration is {{ duration }}, trainer is: {{ trainer }}"
      